### ISSUE TITLE
Update spring cloud aws dependencies

### ISSUE THREAD

**Issue by smilasek** [idealo/spring-cloud-stream-binder-sns#152]
Hey, are there any plans to update lib to spring-cloud-aws v.3.X so it would become fully compatible with spring boot 3? Similar thing was already done for sqs binder. 
Thanks

**Comment by hendrik-nibbrig-idealo** [comment]
Hi there. The update is pretty much complete and we only have to do the release so you can expect that within the week.
Cheers

**Comment by smilasek** [comment]
Great thanks!

**Comment by smilasek** [comment]
any progress here?

**Comment by hendrik-nibbrig-idealo** [comment]
Sorry for not keeping you uptodate. We ran into some issues but are working on it and hope to get it done soon.

**Comment by hendrik-nibbrig-idealo** [comment]
We just created a new release which should be available on maven central shortly

**Comment by smilasek** [comment]
Great thanks! 
Btw, what is the versioning startegy for this repo? Isn't it the same as for sqs binder? Thay have released v3..

**Comment by hendrik-nibbrig-idealo** [comment]
We are using semantic versioning for both repos. Due to some unlucky coincidences we ended up with v2.1.0 We could now artificially increase it to 3.0.0 with a fake commit but decided not to for the moment
